"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Union
from sympy import Expr
from torch._inductor.ir import ComputedBuffer, InputBuffer
from ..cutlass_utils import try_import_cutlass
from cutlass_library import DataType, EpilogueScheduleType, TileDescription

EpilogueFunctor = Any
Buffer = Union[ComputedBuffer, InputBuffer]
CutlassTupleType = Any
CutlassVisitorType = Any
CutlassArgType = Any
if try_import_cutlass():
    _CUTLASS_C_DTYPES = ...
    def create_example_tensors(var_name_to_buffer_name: dict[str, str], name_to_buffer: dict[str, Buffer], size_hint_fn: Callable[[Union[Expr, int]], int]) -> dict[str, python_cutlass.backend.evt.ir.tensor.Tensor]:
        ...
    
    def trace(fn_src: str, example_tensors: dict[str, python_cutlass.backend.evt.ir.tensor.Tensor], accum_type: DataType, output_type: DataType, tile_description: TileDescription, epilogue_schedule: EpilogueScheduleType, name_to_buffer: dict[str, Buffer], size_hint_fn: Callable[[Union[Expr, int]], int], **kwargs: dict[str, Any]) -> tuple[str, str, str]:
        ...
    
