"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from torch.distributed.device_mesh import DeviceMesh
from torch.distributed.tensor._op_schema import OpStrategy

@dataclass
class EinsumDims:
    contracting_dims: list[str]
    batch_dims: list[str]
    lhs_out_only_dims: list[str]
    rhs_out_only_dims: list[str]
    @classmethod
    def parse_equation(cls, equation: str) -> tuple[list[str], str]:
        """
        Parse the einsum equation str to input dim chars and output dim char
        """
        ...
    
    @classmethod
    def parse_dims(cls, input_dims: list[str], output_dim: str) -> EinsumDims:
        """
        Parse the dims and extract the contracting, batch, and free dimensions
        for the left and right hand sides.
        """
        ...
    


def gen_einsum_strategies(equation: str, mesh: DeviceMesh, *, linearity: bool = ...) -> OpStrategy:
    """
    Generate a strategy list for the ops that follow einsum style notation.
    """
    ...

