"""
This type stub file was generated by pyright.
"""

def show() -> str:
    """
    Return a human-readable string with descriptions of the
    configuration of PyTorch.
    """
    ...

def parallel_info() -> str:
    r"""Returns detailed string with parallelization settings"""
    ...

