"""
This type stub file was generated by pyright.
"""

"""Adds docstrings to Tensor functions"""
def add_docstr_all(method: str, docstr: str) -> None:
    ...

common_args = ...
new_common_args = ...
