"""
This type stub file was generated by pyright.
"""

__all__ = ["pytree_register_structseq", "all_return_types"]
all_return_types = ...
return_types = ...
def pytree_register_structseq(cls): # -> None:
    ...

