###############################################################################
#  Pyrefly configuration for PyTorch –                                        #
#  WIP configuration to match mypy while also relaxing rules as               #
#  Pyrefly is in development and the level of strictness in                   #
#  Pytorch is determined                                                      #
###############################################################################

# ---------------------------------------------------------------------------
# What to type‑check
# ---------------------------------------------------------------------------
project_includes = [
    "tools",
]

# ---------------------------------------------------------------------------
# Import fall‑backs - removes strictness
# ---------------------------------------------------------------------------
replace_imports_with_any = [
    "requests.*",
    "yaml.*",
    "linter_test_case.*",
    "expecttest.*",
    "dataclasses_json.*",
    "rich.*",
    "gen_operators_yaml.*",
    "packaging.*",
    "libcst.*",
    "usort.*",
    "isort.*",
    "black.*",
    "tabulate.*",
    "package.oss.utils",
    "gen_op_registration_allowlist.*",
]

# ---------------------------------------------------------------------------
# How to treat untyped code
# ---------------------------------------------------------------------------
# untyped_def_behavior = "check-and-infer-return-any"
# use_untyped_imports = false

# ---------------------------------------------------------------------------
# Current errors in PyTorch across normal and strict Mode
# `error` = true, means the error is turned on
# ---------------------------------------------------------------------------

# # ---------------------------------------------------------------------------
# ## Per-module suppressions
# # ---------------------------------------------------------------------------

[[sub-config]]
matches = "tools/"

[sub-config.errors]
missing-attribute = false # 76 instances
bad-argument-type = false # 31 instances
not-callable = false # 30 instances
no-matching-overload = false # 11 instances
bad-return = false # 9 instances
bad-assignment = false # 6 instances
bad-override = false # 4 instances
unsupported-operand = false # 3 instances
implicitly-defined-attribute = false # 3 instances
invalid-inheritance = false # 2 instances
not-iterable = false # 1 instance
invalid-annotation = false # 1 instance
bad-specialization = false # 1 instance
not-a-type = false # 1 instance
invalid-argument = false # 1 instance
unknown-name = false # 1 instance

###############################################################################
#  End of config                                                              #
###############################################################################