"""
This type stub file was generated by pyright.
"""

import torch._C._onnx as _C_onnx

"""Globals used internally by the ONNX exporter.

Do not use this module outside of `torch.onnx` and its tests.

Be very judicious when adding any new global variables. Do not create new global
variables unless they are absolutely necessary.
"""
class _InternalGlobals:
    """Globals used internally by ONNX exporter.

    NOTE: Be very judicious when adding any new variables. Do not create new
    global variables unless they are absolutely necessary.
    """
    def __init__(self) -> None:
        ...
    
    @property
    def training_mode(self): # -> TrainingMode:
        """The training mode for the exporter."""
        ...
    
    @training_mode.setter
    def training_mode(self, training_mode: _C_onnx.TrainingMode): # -> None:
        ...
    
    @property
    def export_onnx_opset_version(self) -> int:
        """Opset version used during export."""
        ...
    
    @export_onnx_opset_version.setter
    def export_onnx_opset_version(self, value: int): # -> None:
        ...
    
    @property
    def in_onnx_export(self) -> bool:
        """Whether it is in the middle of ONNX export."""
        ...
    
    @in_onnx_export.setter
    def in_onnx_export(self, value: bool): # -> None:
        ...
    
    @property
    def autograd_inlining(self) -> bool:
        """Whether Autograd must be inlined."""
        ...
    
    @autograd_inlining.setter
    def autograd_inlining(self, value: bool): # -> None:
        ...
    


GLOBALS = ...
