"""
This type stub file was generated by pyright.
"""

import os
from torch._C._autograd import DeviceType, _supported_activities, kineto_available
from torch._C._profiler import ProfilerActivity, RecordScope, _ExperimentalConfig
from torch._environment import is_fbcode
from torch.autograd.profiler import KinetoStepTracker, record_function
from torch.optim.optimizer import register_optimizer_step_post_hook
from .profiler import ExecutionTraceObserver, ProfilerAction, _KinetoProfile, profile, schedule, supported_activities, tensorboard_trace_handler
from . import itt

r"""
PyTorch Profiler is a tool that allows the collection of performance metrics during training and inference.
Profiler's context manager API can be used to better understand what model operators are the most expensive,
examine their input shapes and stack traces, study device kernel activity and visualize the execution trace.

.. note::
    An earlier version of the API in :mod:`torch.autograd` module is considered legacy and will be deprecated.

"""
__all__ = ["profile", "schedule", "supported_activities", "tensorboard_trace_handler", "ProfilerAction", "ProfilerActivity", "kineto_available", "DeviceType", "record_function", "ExecutionTraceObserver"]
if os.environ.get("KINETO_USE_DAEMON", "") or (is_fbcode() and os.environ.get("KINETO_FORCE_OPTIMIZER_HOOK", "")):
    _ = ...
