"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from torch import Tensor
from .optimizer import Optimizer, ParamsT, _use_grad_for_differentiable

__all__ = ["Adagrad", "adagrad"]
class Adagrad(Optimizer):
    def __init__(self, params: ParamsT, lr: Union[float, Tensor] = ..., lr_decay: float = ..., weight_decay: float = ..., initial_accumulator_value: float = ..., eps: float = ..., foreach: Optional[bool] = ..., *, maximize: bool = ..., differentiable: bool = ..., fused: Optional[bool] = ...) -> None:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def share_memory(self): # -> None:
        ...
    
    @_use_grad_for_differentiable
    def step(self, closure=...): # -> None:
        """Perform a single optimization step.

        Args:
            closure (Callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        ...
    


def adagrad(params: list[Tensor], grads: list[Tensor], state_sums: list[Tensor], state_steps: list[Tensor], fused: Optional[bool] = ..., grad_scale: Optional[Tensor] = ..., found_inf: Optional[Tensor] = ..., has_sparse_grad: bool = ..., foreach: Optional[bool] = ..., differentiable: bool = ..., has_complex: bool = ..., *, lr: float, weight_decay: float, lr_decay: float, eps: float, maximize: bool): # -> None:
    r"""Functional API that performs Adagrad algorithm computation.

    See :class:`~torch.optim.Adagrad` for details.
    """
    ...

