"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from torch import Tensor
from .optimizer import Optimizer, ParamsT, _disable_dynamo_if_unsupported, _use_grad_for_differentiable

__all__ = ["Adam", "adam"]
class Adam(Optimizer):
    def __init__(self, params: ParamsT, lr: Union[float, Tensor] = ..., betas: tuple[Union[float, Tensor], Union[float, Tensor]] = ..., eps: float = ..., weight_decay: float = ..., amsgrad: bool = ..., *, foreach: Optional[bool] = ..., maximize: bool = ..., capturable: bool = ..., differentiable: bool = ..., fused: Optional[bool] = ..., decoupled_weight_decay: bool = ...) -> None:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    @_use_grad_for_differentiable
    def step(self, closure=...): # -> None:
        """Perform a single optimization step.

        Args:
            closure (Callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        ...
    


@_disable_dynamo_if_unsupported(single_tensor_fn=_single_tensor_adam)
def adam(params: list[Tensor], grads: list[Tensor], exp_avgs: list[Tensor], exp_avg_sqs: list[Tensor], max_exp_avg_sqs: list[Tensor], state_steps: list[Tensor], foreach: Optional[bool] = ..., capturable: bool = ..., differentiable: bool = ..., fused: Optional[bool] = ..., grad_scale: Optional[Tensor] = ..., found_inf: Optional[Tensor] = ..., has_complex: bool = ..., decoupled_weight_decay: bool = ..., *, amsgrad: bool, beta1: float, beta2: float, lr: Union[float, Tensor], weight_decay: float, eps: float, maximize: bool): # -> None:
    r"""Functional API that performs Adam algorithm computation.

    See :class:`~torch.optim.Adam` for details.
    """
    ...

