"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from torch import Tensor
from .optimizer import Optimizer, ParamsT, _disable_dynamo_if_unsupported, _use_grad_for_differentiable

r"""Implementation for the RMSprop algorithm."""
__all__ = ["RMSprop", "rmsprop"]
class RMSprop(Optimizer):
    def __init__(self, params: ParamsT, lr: Union[float, Tensor] = ..., alpha: float = ..., eps: float = ..., weight_decay: float = ..., momentum: float = ..., centered: bool = ..., capturable: bool = ..., foreach: Optional[bool] = ..., maximize: bool = ..., differentiable: bool = ...) -> None:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    @_use_grad_for_differentiable
    def step(self, closure=...): # -> None:
        """Perform a single optimization step.

        Args:
            closure (Callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        ...
    


@_disable_dynamo_if_unsupported(single_tensor_fn=_single_tensor_rmsprop)
def rmsprop(params: list[Tensor], grads: list[Tensor], square_avgs: list[Tensor], grad_avgs: list[Tensor], momentum_buffer_list: list[Tensor], state_steps: list[Tensor], foreach: Optional[bool] = ..., maximize: bool = ..., differentiable: bool = ..., capturable: bool = ..., has_complex: bool = ..., *, lr: float, alpha: float, eps: float, weight_decay: float, momentum: float, centered: bool): # -> None:
    r"""Functional API that performs rmsprop algorithm computation.

    See :class:`~torch.optim.RMSProp` for details.
    """
    ...

