"""
This type stub file was generated by pyright.
"""

from typing import Any
from torch import Tensor
from torch.autograd import Function

if not torch._running_with_deploy():
    _test_lib_def = ...
    _test_lib_impl = ...
    class Realize(Function):
        @staticmethod
        def forward(ctx: object, x: Tensor) -> Tensor:
            ...
        
        @staticmethod
        def backward(ctx: Any, *grad_output: Any) -> Any:
            ...
        
    
    
    def realize(x: Tensor) -> Tensor:
        ...
    
