"""
This type stub file was generated by pyright.
"""

__all__ = []
class IndexExpression:
    """
    Written by Konrad Hinsen <hinsen@cnrs-orleans.fr>
    last revision: 1999-7-23

    Cosmetic changes by T. Oliphant 2001
    """
    def __init__(self, maketuple) -> None:
        ...
    
    def __getitem__(self, item): # -> tuple[Any] | tuple[Any, ...]:
        ...
    


index_exp = ...
s_ = ...
__all__ += ["index_exp", "s_"]
