"""
This type stub file was generated by pyright.
"""

"""Export torch work functions for unary ufuncs, rename/tweak to match numpy.
This listing is further exported to public symbols in the `_numpy/_ufuncs.py` module.
"""
def cbrt(x): # -> Tensor:
    ...

def positive(x):
    ...

def absolute(x): # -> Tensor:
    ...

abs = ...
conj = ...
