"""
This type stub file was generated by pyright.
"""

import torch
from typing import Optional
from torch import Tensor

__all__: list[str] = ...
@torch.jit.script
class _FunctionalSGD:
    def __init__(self, params: list[Tensor], lr: float = ..., momentum: float = ..., dampening: float = ..., weight_decay: float = ..., nesterov: bool = ..., maximize: bool = ..., foreach: bool = ..., fused: bool = ..., _allow_empty_param_list: bool = ...) -> None:
        ...
    
    def step_param(self, param: Tensor, grad: Optional[Tensor]): # -> None:
        """Similar to self.step, but operates on a single parameter and
        its gradient.
        """
        ...
    
    def step(self, gradients: list[Optional[Tensor]]): # -> None:
        ...
    


