"""
This type stub file was generated by pyright.
"""

import functools
from typing import Optional

class CUTLASSOperationSerializer:
    """Serializes and deserializes CUTLASS GEMM operations to/from JSON.

    Handles GemmOperation objects and their nested components (TileDescription, TensorDescription).
    """
    _SUPPORTED_CLASSES: list[str] = ...
    @classmethod
    def serialize(cls, operation: GemmOperation): # -> str:
        """Serialize a GEMM operation to JSON string.

        Args:
            operation: GemmOperation object
            indent: JSON indentation spaces

        Returns:
            str: JSON representation of the operation
        """
        ...
    
    @classmethod
    def deserialize(cls, json_str: str) -> GemmOperation:
        """Deserialize JSON string to a GEMM operation.

        Args:
            json_str: JSON string of a GEMM operation

        Returns:
            GemmOperation: Reconstructed operation
        """
        ...
    


@functools.lru_cache(1)
def get_cutlass_operation_serializer() -> Optional[CUTLASSOperationSerializer]:
    ...

