"""
This type stub file was generated by pyright.
"""

import tensorboard
from torch._vendor.packaging.version import Version
from .writer import FileWriter, SummaryWriter
from tensorboard.summary.writer.record_writer import RecordWriter

if not hasattr(tensorboard, "__version__") or Version(tensorboard.__version__) < Version("1.15"):
    ...
__all__ = ["FileWriter", "RecordWriter", "SummaryWriter"]
