"""
This type stub file was generated by pyright.
"""

from . import functional
from .modules import *
from .modules import MaxPool2d

__all__ = ["BatchNorm2d", "BatchNorm3d", "Conv1d", "Conv2d", "Conv3d", "ConvTranspose1d", "ConvTranspose2d", "ConvTranspose3d", "DeQuantize", "ELU", "Embedding", "EmbeddingBag", "GroupNorm", "Hardswish", "InstanceNorm1d", "InstanceNorm2d", "InstanceNorm3d", "LayerNorm", "LeakyReLU", "Linear", "LSTM", "MultiheadAttention", "Quantize", "ReLU6", "Sigmoid", "Softmax", "Dropout", "PReLU", "FloatFunctional", "FXFloatFunctional", "QFunctional"]
