"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass
from enum import Enum
from typing import Optional
from torch.distributed.tensor import DeviceMesh

_compiled_autograd_enabled: bool = ...
if torch._running_with_deploy():
    def detect_compiled_autograd(): # -> None:
        ...
    
    def compiled_autograd_enabled(): # -> Literal[False]:
        ...
    
else:
    def detect_compiled_autograd(): # -> None:
        ...
    
    def compiled_autograd_enabled(): # -> bool:
        ...
    
@dataclass
class DataParallelMeshInfo:
    mesh: DeviceMesh
    shard_mesh_dim: Optional[int] = ...
    replicate_mesh_dim: Optional[int] = ...
    def __post_init__(self): # -> None:
        ...
    


@dataclass
class FSDPMeshInfo(DataParallelMeshInfo):
    def __post_init__(self): # -> None:
        ...
    


@dataclass
class DDPMeshInfo(DataParallelMeshInfo):
    def __post_init__(self): # -> None:
        ...
    


@dataclass
class HSDPMeshInfo(FSDPMeshInfo, DDPMeshInfo):
    def __post_init__(self): # -> None:
        ...
    


class TrainingState(Enum):
    """Describes the training state of one FSDP state / parameter group."""
    FORWARD = ...
    PRE_BACKWARD = ...
    POST_BACKWARD = ...
    IDLE = ...


