"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from typing import TYPE_CHECKING
from torch.distributed._composable_state import _State
from ._fsdp_api import MixedPrecisionPolicy

if TYPE_CHECKING:
    ...
logger = ...
class FSDPStateContext:
    """This has state shared across FSDP states."""
    def __init__(self) -> None:
        ...
    


def disable_if_config_true(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], OptimizedModule | type[Module] | type[Any] | _Wrapped[Callable[..., Any], object, Callable[..., Any], object] | Callable[..., object] | Any | object | Module]:
    ...

class FSDPState(_State):
    def __init__(self) -> None:
        ...
    
    def init(self, modules: tuple[nn.Module, ...], device: torch.device, mp_policy: MixedPrecisionPolicy, auto_reshard_after_forward: bool) -> None:
        ...
    


