"""
This type stub file was generated by pyright.
"""

import torch
from typing import Optional

def lazy_format_graph_code(name, gm, maybe_id=..., **kwargs): # -> LazyString[Callable[[], Any]]:
    """
    Returns a LazyString that formats the graph code.
    """
    ...

def first_call_function_nn_module_stack(graph: torch.fx.Graph) -> Optional[dict]:
    """
    Returns the nn_module_stack of the first call_function node.
    """
    ...

def get_node_context(node, num_nodes=...) -> str:
    """
    Returns a string of the last num_nodes nodes in the graph.
    """
    ...

