"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, TypeVar

"""Internal flags for ONNX export."""
_is_onnx_exporting = ...
TCallable = TypeVar("TCallable", bound=Callable[..., Any])
def set_onnx_exporting_flag(func: TCallable) -> TCallable:
    ...

