"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class DeviceContext:
    _CONTEXTS: dict[str, Any] = ...
    _CONTEXTS_LOCK = ...
    def __init__(self, device: str) -> None:
        ...
    


def get_device_context(device: Optional[str] = ...) -> DeviceContext:
    ...

