"""
This type stub file was generated by pyright.
"""

from pickle import _Pickler
from .importer import Importer

class _PyTorchLegacyPickler(_Pickler):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def persistent_id(self, obj): # -> Any:
        ...
    


class PackagePickler(_PyTorchLegacyPickler):
    """Package-aware pickler.

    This behaves the same as a normal pickler, except it uses an `Importer`
    to find objects and modules to save.
    """
    def __init__(self, importer: Importer, *args, **kwargs) -> None:
        ...
    
    def save_global(self, obj, name=...): # -> None:
        ...
    


def create_pickler(data_buf, importer, protocol=...): # -> _PyTorchLegacyPickler | PackagePickler:
    ...

