"""
This type stub file was generated by pyright.
"""

"""List of Python standard library modules.

Sadly, there is no reliable way to tell whether a module is part of the
standard library except by comparing to a canonical list.

This is taken from https://github.com/PyCQA/isort/tree/develop/isort/stdlibs,
which itself is sourced from the Python documentation.
"""
def is_stdlib_module(module: str) -> bool:
    ...

stdlib3_9 = ...
